[book]
authors = ["JordiMateoUdL"]
language = "ca"
multilingual = false
src = "src"
title = "HandsOns en Sistemes Operatius per a estudiants del Grau en Enginyeria Informàtica"

[output.html.playground]
editable = true

[output.html.code.hidelines]
sh = "~"
c = "~"